module.exports = (name) => {
  return `{
  "name": "${name}",
  "version": "1.0.0",
  "description": "${name} - generated by sofaStack",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "start": "node index.js",
    "start:local": "DATABASE_URL=postgres://localhost/${name} node index.js",
  },
  "dependencies": {
    "body-parser": "^1.17.1",
    "express": "^4.15.2",
    "request": "^2.81.0"
  }
}`;

};
