import packageJsonGenerator from '../../shared/codeGenrators/packageJsonGenerator';
import {expect} from 'chai';

describe('Package.Json Genrator', () => {

  it('Makes Code As Expected', () => {
    const name = 'test';
    const generatedCode = packageJsonGenerator(name);
    const expected = `{
  "name": "test",
  "version": "1.0.0",
  "description": "test - generated by sofaStack",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "start": "node index.js",
    "start:local": "DATABASE_URL=postgres://localhost/${name} nodemon index.js",
  },
  "dependencies": {
    "body-parser": "^1.17.1",
    "express": "^4.15.2",
    "request": "^2.81.0"
  }
}`;
    expect(generatedCode).to.equal(expected);
  });
});
