const SAVE_MODEL_SUCCESS = 'SAVE_MODEL_SUCCESS';
const UPDATE_MODEL_SUCCESS = 'UPDATE_MODEL_SUCCESS';
const SAVE_PROJECT_NAME_SUCCESS = 'SAVE_PROJECT_NAME_SUCCESS';
const DELETE_MODEL_SUCCESS = 'DELETE_MODEL_SUCCESS';

export { SAVE_MODEL_SUCCESS, SAVE_PROJECT_NAME_SUCCESS, UPDATE_MODEL_SUCCESS, DELETE_MODEL_SUCCESS };
